import { numParse } from '../math/bezier';
export interface DetectedShape { type: string; cx: number; cy: number; w: number; h: number; props: string[]; }
const KAPPA_CIRCLE = 0.551915024494; const KAPPA_CORNER = 0.552228474;
export function detectShape(d: string, globalScale: number): DetectedShape | null {
  if (!d) return null; const EPS = 0.5; const segs: Array<{ cmd: string; nums: number[] }> = []; const re = /([MmLlHhVvCcSsQqTtAaZz])([^MmLlHhVvCcSsQqTtAaZz]*)/g; let m: RegExpExecArray | null;
  while ((m = re.exec(d)) !== null) { const cmd = m[1]; const nums = numParse(m[2].trim().replace(/,/g, ' ').replace(/([^\seE])-/g, '$1 -')); segs.push({ cmd, nums }); }
  const pts: Array<{ x: number; y: number }> = []; const cSegs: Array<{ sx: number; sy: number; cp1x: number; cp1y: number; cp2x: number; cp2y: number; ex: number; ey: number }> = []; let lx = 0, ly = 0, mx = 0, my = 0; let hasOnlyLinear = true, hasCubic = false; const cmdList: string[] = [];
  for (const { cmd, nums } of segs) { const u = cmd.toUpperCase(); cmdList.push(u); if (u === 'M') { lx = nums[0]; ly = nums[1]; mx = lx; my = ly; pts.push({ x: lx, y: ly }); } else if (u === 'm') { lx += nums[0]; ly += nums[1]; mx = lx; my = ly; pts.push({ x: lx, y: ly }); } else if (u === 'L') { lx = nums[0]; ly = nums[1]; pts.push({ x: lx, y: ly }); } else if (u === 'l') { lx += nums[0]; ly += nums[1]; pts.push({ x: lx, y: ly }); } else if (u === 'H') { lx = nums[0]; pts.push({ x: lx, y: ly }); } else if (u === 'h') { lx += nums[0]; pts.push({ x: lx, y: ly }); } else if (u === 'V') { ly = nums[0]; pts.push({ x: lx, y: ly }); } else if (u === 'v') { ly += nums[0]; pts.push({ x: lx, y: ly }); } else if (u === 'C') { hasCubic = true; hasOnlyLinear = false; for (let i = 0; i < nums.length; i += 6) { const sx2 = lx, sy2 = ly; cSegs.push({ sx: sx2, sy: sy2, cp1x: nums[i], cp1y: nums[i+1], cp2x: nums[i+2], cp2y: nums[i+3], ex: nums[i+4], ey: nums[i+5] }); lx = nums[i+4]; ly = nums[i+5]; pts.push({ x: lx, y: ly }); } } else if (u === 'c') { hasCubic = true; hasOnlyLinear = false; for (let i = 0; i < nums.length; i += 6) { const sx2 = lx, sy2 = ly; cSegs.push({ sx: sx2, sy: sy2, cp1x: lx+nums[i], cp1y: ly+nums[i+1], cp2x: lx+nums[i+2], cp2y: ly+nums[i+3], ex: lx+nums[i+4], ey: ly+nums[i+5] }); lx += nums[i+4]; ly += nums[i+5]; pts.push({ x: lx, y: ly }); } } else if (u === 'Z') { pts.push({ x: mx, y: my }); lx = mx; ly = my; } else { hasOnlyLinear = false; } }
  if (!pts.length) return null; const minX = Math.min(...pts.map(p => p.x)); const maxX = Math.max(...pts.map(p => p.x)); const minY = Math.min(...pts.map(p => p.y)); const maxY = Math.max(...pts.map(p => p.y)); const W = maxX - minX; const H = maxY - minY; const cxS = (minX + maxX) / 2; const cyS = (minY + maxY) / 2; const sc = globalScale;
  if (hasCubic && cSegs.length === 4 && cmdList.filter(c => c === 'L' || c === 'H' || c === 'V').length >= 4) { const radii = cSegs.map(s => { const d1 = Math.hypot(s.cp1x - s.sx, s.cp1y - s.sy); const d2 = Math.hypot(s.cp2x - s.ex, s.cp2y - s.ey); return Math.max(d1, d2) / KAPPA_CORNER; }); const avgR = radii.reduce((a, b) => a + b, 0) / radii.length; const allSimilar = radii.every(r => Math.abs(r - avgR) < avgR * 0.2 + EPS); if (allSimilar && avgR > 0.5) { const rw = W * sc; const rh = H * sc; const cr = Math.min(avgR * sc, rw / 2, rh / 2); return { type: '.roundrect', cx: cxS, cy: cyS, w: rw, h: rh, props: [ `<property name="size" type="vec2" value="${(rw/2).toFixed(6)},${(rh/2).toFixed(6)}" />`, `<property name="cornerRadius" type="float" value="${cr.toFixed(6)}" />` ] }; } }
  if (hasOnlyLinear) {
    const uniq = pts.filter((p, i, a) => a.findIndex(q => Math.abs(q.x - p.x) < EPS && Math.abs(q.y - p.y) < EPS) === i);
    if (uniq.length === 2) { const p1x = (uniq[0].x - cxS) * sc; const p1y = (uniq[0].y - cyS) * sc; const p2x = (uniq[1].x - cxS) * sc; const p2y = (uniq[1].y - cyS) * sc; return { type: '.line', cx: cxS, cy: cyS, w: W * sc, h: H * sc, props: [ `<property name="p1" type="vec2" value="${p1x.toFixed(6)},${p1y.toFixed(6)}" />`, `<property name="p2" type="vec2" value="${p2x.toFixed(6)},${p2y.toFixed(6)}" />` ] }; }
    if (uniq.length === 3) { const p1x = (uniq[0].x - cxS) * sc; const p1y = (uniq[0].y - cyS) * sc; const p2x = (uniq[1].x - cxS) * sc; const p2y = (uniq[1].y - cyS) * sc; const p3x = (uniq[2].x - cxS) * sc; const p3y = (uniq[2].y - cyS) * sc; return { type: '.triangle', cx: cxS, cy: cyS, w: W * sc, h: H * sc, props: [ `<property name="p1" type="vec2" value="${p1x.toFixed(6)},${p1y.toFixed(6)}" />`, `<property name="p2" type="vec2" value="${p2x.toFixed(6)},${p2y.toFixed(6)}" />`, `<property name="p3" type="vec2" value="${p3x.toFixed(6)},${p3y.toFixed(6)}" />`, `<property name="closed" type="bool" value="true" />` ] }; }
    if (uniq.length === 4) { const xs = uniq.map(p => p.x); const ys = uniq.map(p => p.y); const uxs = [...new Set(xs.map(v => Math.round(v * 10) / 10))]; const uys = [...new Set(ys.map(v => Math.round(v * 10) / 10))]; if (uxs.length === 2 && uys.length === 2) { const rw = W * sc; const rh = H * sc; return { type: '.rect', cx: cxS, cy: cyS, w: rw, h: rh, props: [ `<property name="size" type="vec2" value="${(rw/2).toFixed(6)},${(rh/2).toFixed(6)}" />` ] }; } return null; }
    if (uniq.length >= 6 && uniq.length % 2 === 0 && uniq.length <= 64) { const sorted = [...uniq].sort((a, b) => Math.atan2(a.y - cyS, a.x - cxS) - Math.atan2(b.y - cyS, b.x - cxS)); const sortedDists = sorted.map(p => Math.hypot(p.x - cxS, p.y - cyS)); const tryAlternating = (outerParity: 0 | 1) => { const outerD = sortedDists.filter((_, i) => i % 2 === outerParity); const innerD = sortedDists.filter((_, i) => i % 2 !== outerParity); const avgOuter = outerD.reduce((a, b) => a + b, 0) / outerD.length; const avgInner = innerD.reduce((a, b) => a + b, 0) / innerD.length; if (avgOuter <= avgInner) return null; const outerOk = outerD.every(d => Math.abs(d - avgOuter) < avgOuter * 0.08 + EPS); const innerOk = innerD.every(d => Math.abs(d - avgInner) < avgInner * 0.08 + EPS); if (!outerOk || !innerOk || (avgOuter - avgInner) / avgOuter < 0.1) return null; return { avgOuter, avgInner, firstOuterIdx: outerParity }; }; const star = tryAlternating(0) || tryAlternating(1); if (star) { const outerR = star.avgOuter * sc; const innerR = star.avgInner * sc; const pointCount = uniq.length / 2; const firstOuter = sorted[star.firstOuterIdx]; const svgAngleDeg = Math.atan2(firstOuter.y - cyS, firstOuter.x - cxS) * 180 / Math.PI; const amOffsetAngle = -(svgAngleDeg + 90); return { type: '.star', cx: cxS, cy: cyS, w: star.avgOuter * 2 * sc, h: star.avgOuter * 2 * sc, props: [ `<property name="pointCount" type="float" value="${pointCount.toFixed(6)}" />`, `<property name="outerRadius" type="float" value="${outerR.toFixed(6)}" />`, `<property name="innerRadius" type="float" value="${innerR.toFixed(6)}" />`, `<property name="offsetAngle" type="float" value="${amOffsetAngle.toFixed(6)}" />` ] }; } }
    if (uniq.length >= 5 && uniq.length <= 32) { const dists = uniq.map(p => Math.hypot(p.x - cxS, p.y - cyS)); const avgD = dists.reduce((a, b) => a + b, 0) / dists.length; const allSameR = dists.every(dd => Math.abs(dd - avgD) < avgD * 0.05 + EPS); if (allSameR) { const amR = avgD * sc; const sorted = [...uniq].sort((a, b) => Math.atan2(a.y - cyS, a.x - cxS) - Math.atan2(b.y - cyS, b.x - cxS)); const firstPt = sorted.reduce((best, p) => { const da = Math.abs(Math.atan2(p.y - cyS, p.x - cxS) - Math.atan2(uniq[0].y - cyS, uniq[0].x - cxS)); const db = Math.abs(Math.atan2(best.y - cyS, best.x - cxS) - Math.atan2(uniq[0].y - cyS, uniq[0].x - cxS)); return da < db ? p : best; }, uniq[0]); const svgAngleDeg = Math.atan2(firstPt.y - cyS, firstPt.x - cxS) * 180 / Math.PI; const amOffsetAngle = -(svgAngleDeg + 90); return { type: '.poly', cx: cxS, cy: cyS, w: amR * 2, h: amR * 2, props: [ `<property name="sideCount" type="float" value="${uniq.length.toFixed(6)}" />`, `<property name="radius" type="float" value="${amR.toFixed(6)}" />`, `<property name="offsetAngle" type="float" value="${amOffsetAngle.toFixed(6)}" />` ] }; } }
  }
  if (hasCubic && cSegs.length === 4) { const rx = W / 2; const ry = H / 2; let isCircular = true; for (const s of cSegs) { const d1x = Math.abs(s.cp1x - s.sx); const d1y = Math.abs(s.cp1y - s.sy); const d2x = Math.abs(s.cp2x - s.ex); const d2y = Math.abs(s.cp2y - s.ey); const maxD1 = Math.max(d1x, d1y); const maxD2 = Math.max(d2x, d2y); const expectedR = Math.max(rx, ry) * KAPPA_CIRCLE; if (Math.abs(maxD1 - expectedR) > expectedR * 0.15 && Math.abs(maxD2 - expectedR) > expectedR * 0.15) { isCircular = false; break; } } if (isCircular) { const amW = W * sc; const amH = H * sc; return { type: '.circle', cx: cxS, cy: cyS, w: amW, h: amH, props: [ `<property name="size" type="vec2" value="${(amW/2).toFixed(6)},${(amH/2).toFixed(6)}" />` ] }; } }
  return null;
}
