import type { ShapeOpts, DetectedShape } from '../types';
import { hexToAM } from '../styles/colors';
const F = (n: number): string => isFinite(n) ? n.toFixed(6) : '0.000000';
export interface BuildShapeOptions { id: number; label: string; amPath: string; fillColor: string; opts: ShapeOpts; detected: DetectedShape | null; }
function escapeXml(str: string): string { if (!str) return 'Shape'; return str.replace(/[<>&"']/g, '').replace(/\s+/g, ' ').trim() || 'Shape'; }
export function buildShapeXml(params: BuildShapeOptions): string {
  const { id, label, amPath, fillColor, opts, detected } = params; const safeLabel = escapeXml(label);
  let transformXml = `  <transform>\n`; transformXml += `    <location value="${F(opts.tcx)},${F(opts.tcy)},0.000000" />\n`;
  if (opts.primitiveScaleX !== undefined && opts.primitiveScaleY !== undefined) { const sx = opts.primitiveScaleX; const sy = opts.primitiveScaleY; if (Math.abs(sx - 1) > 0.0001 || Math.abs(sy - 1) > 0.0001) transformXml += `    <scale value="${F(sx)},${F(sy)}" />\n`; }
  const layerOpacity = opts.layerOpacity !== undefined ? opts.layerOpacity : 1.0; if (layerOpacity < 0.999) transformXml += `    <opacity value="${F(layerOpacity)}" />\n`;
  transformXml += `  </transform>\n`;
  const fillColorXml = `  <fillColor value="#${fillColor}" />\n`;
  let gradientXml = ''; let amFillType = opts.fillType;
  if (opts.fillType.startsWith('gradient')) { amFillType = 'gradient'; const gType = opts.fillType.replace('gradient-', ''); let sc: string, ec: string; if (opts._isSvgGradient && opts._gradStartAM && opts._gradEndAM) { sc = opts._gradStartAM; ec = opts._gradEndAM; } else { sc = (opts.gradStart !== '#000000') ? hexToAM(opts.gradStart) : fillColor; ec = hexToAM(opts.gradEnd); } let gradStart = '0.000000,0.000000'; let gradEnd = '1.000000,1.000000'; if (opts._gradStartEnd) { gradStart = opts._gradStartEnd.start; gradEnd = opts._gradStartEnd.end; } gradientXml = `  <gradient type="${gType}" startColor="#${sc}" endColor="#${ec}" start="${gradStart}" end="${gradEnd}" />\n`; } else if (opts.fillType === 'none' || detected?.type === '.line') { amFillType = 'none'; }
  let strokeXml = ''; if (opts.useStroke && opts.strokeSize > 0) { const strokeSizeScaled = opts.strokeSize * (opts.globalScale || 1); const joinAttr = opts.strokeJoin ? ` join="${opts.strokeJoin}"` : ''; const capVal = opts.strokeCap || ''; const capAttr = (capVal && capVal !== 'round') ? ` cap="${capVal}"` : ''; const colorXml = opts.useStrokeColor ? `    <color value="#${hexToAM(opts.strokeColor)}" />\n` : ''; strokeXml = `  <path-stroke direction="centered"${joinAttr}${capAttr} end-size="1.500000">\n`; strokeXml += colorXml; strokeXml += `    <size value="${F(strokeSizeScaled)}" />\n`; strokeXml += `  </path-stroke>\n`; }
  let contentXml = ''; const blendAttr = opts.blending ? ` blending="${opts.blending}"` : '';
  if (detected) { contentXml = detected.props.map(p => `  ${p}`).join('\n') + '\n'; let xml = `<shape id="${id}" label="${safeLabel}" startTime="${opts.startTime}" endTime="${opts.endTime}" fillType="${amFillType}"${blendAttr} mediaFillMode="fill" s="${detected.type}">\n`; xml += transformXml + fillColorXml + gradientXml + strokeXml + contentXml; xml += `</shape>\n`; return xml; }
  else { const subpaths = amPath.match(/[Mm][^Mm]*/g) || [amPath]; const cleanSubs = subpaths.map(s => s.trim()).filter(s => s.length > 1); if (cleanSubs.length >= 2) { contentXml = `  <path>\n`; cleanSubs.forEach((sub, idx) => { const sp = sub.endsWith('Z') || sub.endsWith('z') ? sub : sub + ' Z'; if (idx === 0) contentXml += `    <contour d="${sp}" />\n`; else contentXml += `    <contour exclude="true" d="${sp}" />\n`; }); contentXml += `  </path>\n`; } else { contentXml = `  <path d="${amPath.trim()}" />\n`; } let xml = `<shape id="${id}" label="${safeLabel}" startTime="${opts.startTime}" endTime="${opts.endTime}" fillType="${amFillType}"${blendAttr} mediaFillMode="fill">\n`; xml += transformXml + fillColorXml + gradientXml + strokeXml + contentXml; xml += `</shape>\n`; return xml; }
}
