import type { ColorInfo, GradientInfo } from '../types';
export const NAMED_COLORS: Record<string, string | null> = { black: '000000', white: 'ffffff', red: 'ff0000', green: '008000', blue: '0000ff', yellow: 'ffff00', cyan: '00ffff', magenta: 'ff00ff', orange: 'ffa500', purple: '800080', pink: 'ffc0cb', brown: 'a52a2a', gray: '808080', grey: '808080', lime: '00ff00', maroon: '800000', navy: '000080', olive: '808000', teal: '008080', silver: 'c0c0c0', aqua: '00ffff', fuchsia: 'ff00ff', gold: 'ffd700', coral: 'ff7f50', salmon: 'fa8072', khaki: 'f0e68c', indigo: '4b0082', violet: 'ee82ee', crimson: 'dc143c', turquoise: '40e0d0', sienna: 'a0522d', tan: 'd2b48c', lavender: 'e6e6fa', beige: 'f5f5dc', ivory: 'fffff0', mintcream: 'f5fffa', snow: 'fffafa', wheat: 'f5deb3', chocolate: 'd2691e', tomato: 'ff6347', hotpink: 'ff69b4', deeppink: 'ff1493', dodgerblue: '1e90ff', royalblue: '4169e1', steelblue: '4682b4', skyblue: '87ceeb', lightyellow: 'ffffe0', lightgreen: '90ee90', lightblue: 'add8e6', lightgray: 'd3d3d3', lightgrey: 'd3d3d3', darkred: '8b0000', darkgreen: '006400', darkblue: '00008b', darkorange: 'ff8c00', darkgray: 'a9a9a9', darkgrey: 'a9a9a9', transparent: '00000000', none: null };
export function parseCssColor(raw: string): { r: number; g: number; b: number; a: number } | null {
  if (!raw) return null; raw = raw.trim().toLowerCase(); if (raw === 'none' || raw === 'transparent') return null;
  if (Object.prototype.hasOwnProperty.call(NAMED_COLORS, raw)) { if (NAMED_COLORS[raw] === null) return null; const h = NAMED_COLORS[raw] as string; return { r: parseInt(h.slice(0, 2), 16), g: parseInt(h.slice(2, 4), 16), b: parseInt(h.slice(4, 6), 16), a: 255 }; }
  const h2i = (s: string) => parseInt(s, 16); const hm = raw.match(/^#([0-9a-f]{3,8})$/);
  if (hm) { let h = hm[1]; if (h.length === 3) h = h[0]+h[0]+h[1]+h[1]+h[2]+h[2]; if (h.length === 4) h = h[0]+h[0]+h[1]+h[1]+h[2]+h[2]+h[3]+h[3]; if (h.length === 6) return { r: h2i(h.slice(0,2)), g: h2i(h.slice(2,4)), b: h2i(h.slice(4,6)), a: 255 }; if (h.length === 8) return { r: h2i(h.slice(0,2)), g: h2i(h.slice(2,4)), b: h2i(h.slice(4,6)), a: h2i(h.slice(6,8)) }; }
  const rgb = raw.match(/rgba?\(\s*([\d.]+)(%)?(?:\s*,\s*|\s+)([\d.]+)(%)?(?:\s*,\s*|\s+)([\d.]+)(%)?(?:(?:\s*,\s*|\s*\/\s*)([\d.]+)(%)?)?\s*\)/);
  if (rgb) { const parseC = (v: string, isPct: boolean) => isPct ? Math.round(parseFloat(v) * 2.55) : Math.round(parseFloat(v)); const parseA = (v?: string, isPct?: boolean) => v ? (isPct ? Math.round(parseFloat(v) * 2.55) : Math.round(parseFloat(v) * 255)) : 255; return { r: parseC(rgb[1], !!rgb[2]), g: parseC(rgb[3], !!rgb[4]), b: parseC(rgb[5], !!rgb[6]), a: parseA(rgb[7], !!rgb[8]) }; }
  const hsl = raw.match(/hsla?\(\s*([\d.]+)\s*,\s*([\d.]+)%\s*,\s*([\d.]+)%(?:(?:\s*,\s*|\s*\/\s*)([\d.]+)(%)?)?\s*\)/);
  if (hsl) { const h = parseFloat(hsl[1]) / 360; const s = parseFloat(hsl[2]) / 100; const l = parseFloat(hsl[3]) / 100; const a = hsl[4] ? (hsl[5] ? Math.round(parseFloat(hsl[4]) * 2.55) : Math.round(parseFloat(hsl[4]) * 255)) : 255; let r: number, g: number, b: number; if (s === 0) { r = g = b = Math.round(l * 255); } else { const hue2rgb = (p: number, q: number, t: number) => { if (t < 0) t += 1; if (t > 1) t -= 1; if (t < 1/6) return p + (q-p) * 6 * t; if (t < 1/2) return q; if (t < 2/3) return p + (q-p) * (2/3-t) * 6; return p; }; const q = l < 0.5 ? l * (1+s) : l+s-l*s; const p = 2*l - q; r = Math.round(hue2rgb(p, q, h+1/3) * 255); g = Math.round(hue2rgb(p, q, h) * 255); b = Math.round(hue2rgb(p, q, h-1/3) * 255); } return { r, g, b, a }; }
  return null;
}
export function parseStyleObj(str: string | null): Record<string, string> { const o: Record<string, string> = {}; if (!str) return o; str.split(';').forEach(p => { const i = p.indexOf(':'); if (i < 0) return; o[p.slice(0, i).trim().toLowerCase()] = p.slice(i+1).trim(); }); return o; }
export function parseSvgStyles(svgEl: Element): Record<string, Record<string, string>> { const classMap: Record<string, Record<string, string>> = {}; svgEl.querySelectorAll('style').forEach(styleEl => { const txt = styleEl.textContent || ''; const ruleRe = /([^{,]+)\{([^}]*)\}/g; let m: RegExpExecArray | null; while ((m = ruleRe.exec(txt)) !== null) { const selectors = m[1].split(','); const props = parseStyleObj(m[2]); selectors.forEach(sel => { const classes: string[] = sel.match(/\.([^\s.#:\[]+)/g) || []; classes.forEach(c => { const name = c.slice(1); if (!classMap[name]) classMap[name] = {}; Object.assign(classMap[name], props); }); }); } }); return classMap; }
export function hexToAM(hex: string, alpha = 255): string { const c = parseCssColor(hex); if (!c) return 'ff000000'; const h2 = (n: number) => Math.max(0, Math.min(255, n)).toString(16).padStart(2, '0'); return `${h2(alpha)}${h2(c.r)}${h2(c.g)}${h2(c.b)}`; }
export function getFillColorV7(el: Element, classMap: Record<string, Record<string, string>>, gradMap: Record<string, GradientInfo>): ColorInfo | null {
  let fillRaw: string | null = null; let opacityRaw: string | null = null; let node: Element | null = el;
  while (node && node.getAttribute) { const sty = parseStyleObj(node.getAttribute('style')); if (!fillRaw && sty['fill']) { if (sty['fill'] !== 'inherit') fillRaw = sty['fill']; } if (!fillRaw) { const cls = (node.getAttribute('class') || '').trim().split(/\s+/); for (const c of cls) { if (classMap[c] && classMap[c]['fill']) { fillRaw = classMap[c]['fill']; break; } } } if (!fillRaw) { const f = node.getAttribute('fill'); if (f && f !== 'inherit') fillRaw = f; } if (!opacityRaw) { const op = sty['fill-opacity'] || node.getAttribute('fill-opacity'); if (op != null && op !== '') opacityRaw = op; } if (fillRaw && opacityRaw) break; node = node.parentElement; }
  if (!fillRaw) fillRaw = '#000000';
  const urlMatch = fillRaw.match(/^url\(#([^)]+)\)$/);
  if (urlMatch && gradMap) { const gradId = urlMatch[1]; const grad = gradMap[gradId]; if (grad && grad.stops.length >= 1) { const startStop = grad.stops[0]; const endStop = grad.stops[grad.stops.length - 1]; return { amColor: startStop.amColor, cssHex: startStop.cssHex, isGradient: true, gradType: grad.type, gradStartAM: startStop.amColor, gradEndAM: endStop.amColor, gradStops: grad.stops, gradInfo: grad }; } return null; }
  const c = parseCssColor(fillRaw); if (!c) return null; const opacity = opacityRaw != null ? Math.max(0, Math.min(1, parseFloat(opacityRaw))) : 1.0; const alpha = Math.round((c.a / 255) * opacity * 255); const h2 = (n: number) => Math.max(0, Math.min(255, Math.round(n))).toString(16).padStart(2, '0'); return { amColor: `${h2(alpha)}${h2(c.r)}${h2(c.g)}${h2(c.b)}`, cssHex: `#${h2(c.r)}${h2(c.g)}${h2(c.b)}` };
}
