import type { StrokeInfo } from '../types';
import { parseStyleObj } from './colors';
export function getStrokeInfo(el: Element, classMap: Record<string, Record<string, string>> = {}): StrokeInfo {
  let strokeRaw: string | null = null; let widthRaw: string | null = null; let fillRaw: string | null = null; let linecap: string | null = null; let linejoin: string | null = null; let opacityRaw: string | null = null;
  let node: Element | null = el;
  while (node && node.getAttribute) { const sty = parseStyleObj(node.getAttribute('style')); if (!strokeRaw) { const s = sty['stroke'] || node.getAttribute('stroke'); if (s && s !== 'inherit' && s !== 'none') strokeRaw = s; } if (!widthRaw) { const w = sty['stroke-width'] || node.getAttribute('stroke-width'); if (w != null && w !== '') widthRaw = w; } if (!fillRaw) { const f = sty['fill'] || node.getAttribute('fill'); if (f && f !== 'inherit') fillRaw = f; } if (!linecap) { const c = sty['stroke-linecap'] || node.getAttribute('stroke-linecap'); if (c && c !== 'inherit') linecap = c; } if (!linejoin) { const j = sty['stroke-linejoin'] || node.getAttribute('stroke-linejoin'); if (j && j !== 'inherit') linejoin = j; } if (!opacityRaw) { const o = sty['stroke-opacity'] || node.getAttribute('stroke-opacity'); if (o != null && o !== '') opacityRaw = o; } if (strokeRaw && fillRaw && widthRaw && linecap && linejoin && opacityRaw) break; node = node.parentElement; }
  if (!strokeRaw || !widthRaw) { const cls = (el.getAttribute('class') || '').trim().split(/\s+/); for (const c of cls) { if (classMap[c]) { if (!strokeRaw && classMap[c]['stroke']) strokeRaw = classMap[c]['stroke']; if (!widthRaw && classMap[c]['stroke-width']) widthRaw = classMap[c]['stroke-width']; if (!linecap && classMap[c]['stroke-linecap']) linecap = classMap[c]['stroke-linecap']; if (!linejoin && classMap[c]['stroke-linejoin']) linejoin = classMap[c]['stroke-linejoin']; } } }
  const isStrokeOnly = fillRaw === 'none' || fillRaw === 'transparent' || !fillRaw;
  let width: number | null = null; if (widthRaw) { const wStr = widthRaw.toString().trim(); const numMatch = wStr.match(/^([\d.]+)/); if (numMatch) { width = parseFloat(numMatch[1]); if (wStr.includes('pt')) width = width * 1.333; else if (wStr.includes('em')) width = width * 16; else if (wStr.includes('mm')) width = width * 3.78; } }
  return { raw: strokeRaw, width, isStrokeOnly, linecap, linejoin };
}
