import type { ParsedPath, ParseResult, Matrix, ColorInfo, StrokeInfo } from '../types';
import { parseSvgStyles, getFillColorV7 } from '../styles/colors';
import { parseGradientDefs } from '../styles/gradients';
import { getStrokeInfo } from '../styles/strokes';
import { getAccumulatedTransform, isIdentityMatrix, parseTransformMatrix } from '../math/matrix';
import { shapeToD } from './svg-shapes';
export function sanitizeLabel(str: string): string { if (!str) return 'Shape'; return str.replace(/^<(.+)>$/, '$1').replace(/[<>&"']/g, '').replace(/·/g, '-').replace(/\s+/g, ' ').trim() || 'Shape'; }
export function getLayerInfo(el: Element, index: number): { label: string; layerName: string | null; groupPath: string[]; isFromLayer: boolean; } {
  const groupPath: string[] = []; let node: Element | null = el.parentElement;
  while (node && node.tagName && node.tagName.toLowerCase() !== 'svg') { if (node.tagName.toLowerCase() === 'g') { const inkLabel = node.getAttribute('inkscape:label'); const dataName = node.getAttribute('data-name'); const ariaLabel = node.getAttribute('aria-label'); const titleEl = node.querySelector(':scope > title'); const titleText = titleEl ? titleEl.textContent!.trim() : ''; const nodeId = node.getAttribute('id') || ''; const classAttr = node.getAttribute('class') || ''; let label: string | null = inkLabel || dataName || ariaLabel || titleText || null; if (!label && nodeId && !nodeId.match(/^(g\d+|layer\d*|group\d*|svg\d*|G\d+|Layer\d*|Group\d*|clip\d*|mask\d*|defs\d*)$/i)) label = nodeId; if (!label && classAttr && !classAttr.match(/^\d/)) { const firstClass = classAttr.split(/\s+/)[0]; if (firstClass && firstClass.length > 1 && !firstClass.match(/^(cls|st|fill|stroke|color)\d*$/i)) label = firstClass; } if (label) groupPath.unshift(sanitizeLabel(label.trim())); else if (node.childElementCount > 1) { const parent = node.parentElement; let gIndex = 1; if (parent) { const siblings = Array.from(parent.children).filter(c => c.tagName && c.tagName.toLowerCase() === 'g'); gIndex = siblings.indexOf(node) + 1; } groupPath.unshift(`Group_${gIndex}`); } } node = node.parentElement; }
  const selfId = el.getAttribute('id') || ''; const selfDataName = el.getAttribute('data-name') || ''; const selfInkLabel = el.getAttribute('inkscape:label') || ''; const selfLabelRaw = selfInkLabel || selfDataName || (selfId && !selfId.match(/^(path|rect|circle|ellipse|polygon|line|polyline|use|shape|Path|Rect|Circle|Ellipse)\d+$/i) ? selfId : null); const selfLabel = selfLabelRaw ? sanitizeLabel(selfLabelRaw) : null; const idx = String(index + 1).padStart(3, '0'); const topGroupName = groupPath.length > 0 ? groupPath[0] : null; const innerGroupName = groupPath.length > 0 ? groupPath[groupPath.length - 1] : null; let fullLabel: string; if (selfLabel && selfLabel !== topGroupName && selfLabel !== innerGroupName) fullLabel = selfLabel; else if (innerGroupName) fullLabel = `${innerGroupName.slice(0, 20)}_${idx}`; else if (topGroupName) fullLabel = `${topGroupName.slice(0, 20)}_${idx}`; else fullLabel = `Shape_${idx}`;
  return { groupPath, layerName: topGroupName, label: fullLabel, isFromLayer: groupPath.length > 0 };
}
export function getLayerOpacity(el: Element, classMap: Record<string, Record<string, string>> = {}): number { let result = 1.0; let node: Element | null = el; while (node && node.getAttribute) { const sty = (node.getAttribute('style') || '').split(';').reduce((acc, p) => { const i = p.indexOf(':'); if (i > 0) acc[p.slice(0, i).trim().toLowerCase()] = p.slice(i + 1).trim(); return acc; }, {} as Record<string, string>); let op: string | null = sty['opacity'] || node.getAttribute('opacity'); if (!op && classMap) { const cls = (node.getAttribute('class') || '').trim().split(/\s+/); for (const c of cls) { if (classMap[c] && classMap[c]['opacity']) { op = classMap[c]['opacity']; break; } } } if (op != null && op !== '' && op !== 'inherit') { const v = parseFloat(op); if (!isNaN(v)) result *= Math.max(0, Math.min(1, v)); } node = node.parentElement; } return Math.max(0, Math.min(1, result)); }
export function isInsideDefs(el: Element): boolean { let node: Element | null = el.parentElement; while (node && node.tagName) { const tag = node.tagName.toLowerCase(); if (tag === 'defs' || tag === 'clippath' || tag === 'mask' || tag === 'pattern' || tag === 'symbol') return true; if (tag === 'svg') break; node = node.parentElement; } if (el.tagName && el.tagName.toLowerCase() === 'clippath') return true; return false; }
export function parseSvg(txt: string): ParseResult {
  const emptyResult: ParseResult = { parsedPaths: [], svgCloneHtml: '', svgDims: null, hasAiMatrix: false, strokeOnlyCount: 0, hasOnlyRaster: false, classMap: {}, gradMap: {}, clipperMap: {} };
  if (!txt) return emptyResult; const parser = new DOMParser(); const doc = parser.parseFromString(txt, 'image/svg+xml'); if (doc.querySelector('parsererror')) return emptyResult; const svgEl = doc.documentElement; if (!svgEl || svgEl.tagName.toLowerCase() !== 'svg') return emptyResult;
  const vbAttr = svgEl.getAttribute('viewBox'); const vbParts = (vbAttr || '').trim().split(/[\s,]+/).map(Number); const vbX = vbParts[0] || 0; const vbY = vbParts[1] || 0; let vbW = vbParts[2] || parseFloat(svgEl.getAttribute('width') || '0') || 1080; let vbH = vbParts[3] || parseFloat(svgEl.getAttribute('height') || '0') || 1080; if (!vbW) vbW = 1080; if (!vbH) vbH = 1080;
  const classMap = parseSvgStyles(svgEl); const gradMap = parseGradientDefs(svgEl); const clipperMap: Record<string, { d: string; mat: Matrix | null }> = {};
  svgEl.querySelectorAll('clipPath').forEach(cp => { const id = cp.getAttribute('id'); if (!id) return; const child = Array.from(cp.childNodes).find((n): n is Element => !!(n as Element).tagName) as Element | undefined; if (!child) return; const d = child.tagName.toLowerCase() === 'path' ? child.getAttribute('d') : shapeToD(child); if (d) { const cpTransform = cp.getAttribute('clipPathTransform') || cp.getAttribute('transform'); const cpMat = cpTransform ? parseTransformMatrix(cpTransform) : null; clipperMap[id] = { d, mat: isIdentityMatrix(cpMat) ? null : cpMat }; } });
  const parsedPaths: ParsedPath[] = []; let pathIndex = 0; let hasAiMatrix = false; let strokeOnlyCount = 0; let hasOnlyRaster = true; let hasAnyShape = false;
  const allElements = svgEl.querySelectorAll('path,rect,circle,ellipse,polygon,polyline,line');
  allElements.forEach(el => {
    if (isInsideDefs(el)) return; const tag = el.tagName.toLowerCase().replace(/.*:/, ''); let d = tag === 'path' ? (el.getAttribute('d') || '') : (shapeToD(el) || ''); if (!d || d.trim().length < 3) return;
    hasAnyShape = true; hasOnlyRaster = false; const color: ColorInfo | null = getFillColorV7(el, classMap, gradMap); const svgStroke: StrokeInfo = getStrokeInfo(el, classMap); const layerInfo = getLayerInfo(el, pathIndex); const mat = getAccumulatedTransform(el, svgEl); const hasMatrix = !isIdentityMatrix(mat);
    if (hasMatrix) { const transforms = el.getAttribute('transform') || ''; if (/matrix/i.test(transforms) || txt.includes('matrix(1.3333333')) hasAiMatrix = true; }
    const layerOpacity = getLayerOpacity(el, classMap); if (svgStroke.isStrokeOnly) strokeOnlyCount++;
    let clipPathRef: string | null = null; let clipType: string | null = null; let clipGroupMat: Matrix | null = null;
    const selfClip = el.getAttribute('clip-path'); if (selfClip) { clipPathRef = selfClip.match(/url\(#([^)]+)\)/)?.[1] || null; if (clipPathRef) { clipType = 'direct'; clipGroupMat = hasMatrix ? mat : null; } } else { let clipNode: Element | null = el.parentElement; while (clipNode && clipNode.tagName && clipNode.tagName.toLowerCase() !== 'svg') { const cp = clipNode.getAttribute('clip-path'); if (cp) { clipPathRef = cp.match(/url\(#([^)]+)\)/)?.[1] || null; if (clipPathRef) { clipType = clipNode.tagName.toLowerCase() === 'g' ? 'group' : 'direct'; const cgm = getAccumulatedTransform(clipNode, svgEl); clipGroupMat = isIdentityMatrix(cgm) ? null : cgm; } break; } clipNode = clipNode.parentElement; } }
    parsedPaths.push({ el, d, index: pathIndex, label: layerInfo.label, layerName: layerInfo.layerName, groupPath: layerInfo.groupPath, isFromLayer: layerInfo.isFromLayer, color, svgStroke, mat: hasMatrix ? mat : null, hasMatrix, layerOpacity, clipPathRef, clipType, clipGroupMat }); pathIndex++;
  });
  if (!hasAnyShape) { const rasterEls = svgEl.querySelectorAll('image,use,symbol,text'); if (rasterEls.length > 0) hasOnlyRaster = true; }
  const svgClone = svgEl.cloneNode(true) as Element; svgClone.querySelectorAll('script').forEach(s => s.remove()); svgClone.removeAttribute('width'); svgClone.removeAttribute('height'); if (!svgClone.getAttribute('viewBox')) svgClone.setAttribute('viewBox', `${vbX} ${vbY} ${vbW} ${vbH}`);
  const serializer = new XMLSerializer(); const svgCloneHtml = serializer.serializeToString(svgClone);
  return { parsedPaths, svgCloneHtml, svgDims: { vbX, vbY, vbW, vbH, W: vbW, H: vbH }, hasAiMatrix, strokeOnlyCount, hasOnlyRaster, classMap, gradMap, clipperMap };
}
